def get_gaps_full(conn):
    query = """
    WITH BASE AS (
    SELECT 
        SITE_NAME,
        DATA,
        HORA,
        FLUXO,
        TICKET,
        CASE 
            WHEN FLUXO > 0 AND (TICKET IS NULL OR TICKET = '') THEN 1
            WHEN FLUXO = 0 AND (TICKET IS NULL OR TICKET = '') THEN 2
            WHEN FLUXO > 0 AND (TICKET IS NOT NULL AND TICKET <> '') THEN 3
            WHEN FLUXO = 0 AND (TICKET > 0) THEN 4
            ELSE NULL
        END AS ID_HORA
    FROM DS_INTEGRACAO_GAP_FULL
)

SELECT
    SITE_NAME,
    DATA,

    MAX(CASE WHEN HORA = 10 THEN ID_HORA END) AS H10,
    MAX(CASE WHEN HORA = 11 THEN ID_HORA END) AS H11,
    MAX(CASE WHEN HORA = 12 THEN ID_HORA END) AS H12,
    MAX(CASE WHEN HORA = 13 THEN ID_HORA END) AS H13,
    MAX(CASE WHEN HORA = 14 THEN ID_HORA END) AS H14,
    MAX(CASE WHEN HORA = 15 THEN ID_HORA END) AS H15,
    MAX(CASE WHEN HORA = 16 THEN ID_HORA END) AS H16,
    MAX(CASE WHEN HORA = 17 THEN ID_HORA END) AS H17,
    MAX(CASE WHEN HORA = 18 THEN ID_HORA END) AS H18,
    MAX(CASE WHEN HORA = 19 THEN ID_HORA END) AS H19,
    MAX(CASE WHEN HORA = 20 THEN ID_HORA END) AS H20,
    MAX(CASE WHEN HORA = 21 THEN ID_HORA END) AS H21,
    MAX(CASE WHEN HORA = 22 THEN ID_HORA END) AS H22

FROM BASE
GROUP BY SITE_NAME, DATA
ORDER BY DATA DESC, SITE_NAME ASC;;
    """
    cursor = conn.cursor()
    cursor.execute(query)
    columns = [column[0] for column in cursor.description]
    return [dict(zip(columns, row)) for row in cursor.fetchall()]
